version: 2.1

jobs:
  consec-image:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run:
          name: "Build Image"
          command: "docker build -t getting-started:new ."
      - run:
          name: "Download TCS CLI"
          command: >-
              wget https://www.tenable.com/downloads/api/v2/pages/tenable-cs/files/tenable.cs-cli_latest_Linux_x86_64.tar.gz &&
              file_name=`echo https://www.tenable.com/downloads/api/v2/pages/tenable-cs/files/tenable.cs-cli_latest_Linux_x86_64.tar.gz | cut -f10 -d "/"` &&
              tar -xf $file_name && chmod 777 tcs
      - run:
          name: "TCS Version"
          command: "./tcs version"

      - run:
          name: "TCS Image Scan"
          command: "./tcs scan -t=container-image --image=docker-daemon:getting-started:new --wait"
      - run:
          name: "Report File"
          command: >-
              ls ./report
workflows:
  consec-workflow:
    jobs:
      - consec-image
